import { Person, Wife, Source, City, TypePerson, TypeMother, Gender } from '@/types';

// ===== Mock Cities =====
export const mockCities: City[] = [
  { id: 1, name: 'تريم', country: 'اليمن' },
  { id: 2, name: 'سيئون', country: 'اليمن' },
  { id: 3, name: 'المكلا', country: 'اليمن' },
  { id: 4, name: 'عدن', country: 'اليمن' },
  { id: 5, name: 'صنعاء', country: 'اليمن' },
  { id: 6, name: 'حضرموت', country: 'اليمن' },
  { id: 7, name: 'مكة المكرمة', country: 'السعودية' },
  { id: 8, name: 'المدينة المنورة', country: 'السعودية' },
  { id: 9, name: 'جدة', country: 'السعودية' },
  { id: 10, name: 'جاكرتا', country: 'إندونيسيا' },
  { id: 11, name: 'سنغافورة', country: 'سنغافورة' },
  { id: 12, name: 'القاهرة', country: 'مصر' },
  { id: 13, name: 'دمشق', country: 'سوريا' },
  { id: 14, name: 'بغداد', country: 'العراق' },
  { id: 15, name: 'الشحر', country: 'اليمن' },
];

// ===== Mock Persons (Hierarchical Family Tree) =====
const now = new Date().toISOString();

export const mockPersons: Person[] = [
  // الجد الأكبر (الجذر)
  {
    id: 1,
    name: 'أحمد بن علي',
    kunya: 'أبو محمد',
    title: 'الشيخ',
    gender: 'M' as Gender,
    parent_id: null,
    type_person: TypePerson.included,
    birth_year: 1200,
    death_year: 1280,
    number: null,
    birth_place_id: 1,
    death_place_id: 1,
    mother_id: null,
    type_mother: TypeMother.alawi,
    number_mother: null,
    name_mother: '',
    note: 'الجد الأكبر للعائلة',
    file: null,
    created_at: now,
    updated_at: now,
  },
  // الجيل الثاني
  {
    id: 2,
    name: 'محمد بن أحمد',
    kunya: 'أبو عبدالله',
    title: 'الإمام',
    gender: 'M' as Gender,
    parent_id: 1,
    type_person: TypePerson.included,
    birth_year: 1230,
    death_year: 1310,
    number: null,
    birth_place_id: 1,
    death_place_id: 2,
    mother_id: null,
    type_mother: TypeMother.alawi,
    number_mother: null,
    name_mother: 'فاطمة بنت حسين',
    note: '',
    file: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 3,
    name: 'عبدالله بن أحمد',
    kunya: 'أبو حسن',
    title: '',
    gender: 'M' as Gender,
    parent_id: 1,
    type_person: TypePerson.extinct,
    birth_year: 1235,
    death_year: 1300,
    number: null,
    birth_place_id: 1,
    death_place_id: 1,
    mother_id: null,
    type_mother: TypeMother.Arab,
    number_mother: null,
    name_mother: '',
    note: 'انقرض عقبه',
    file: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 4,
    name: 'فاطمة بنت أحمد',
    kunya: '',
    title: '',
    gender: 'F' as Gender,
    parent_id: 1,
    type_person: TypePerson.females_only,
    birth_year: 1240,
    death_year: 1320,
    number: 3,
    birth_place_id: 1,
    death_place_id: 7,
    mother_id: null,
    type_mother: TypeMother.alawi,
    number_mother: null,
    name_mother: '',
    note: '',
    file: null,
    created_at: now,
    updated_at: now,
  },
  // الجيل الثالث
  {
    id: 5,
    name: 'علي بن محمد',
    kunya: 'أبو الحسن',
    title: 'السيد',
    gender: 'M' as Gender,
    parent_id: 2,
    type_person: TypePerson.included,
    birth_year: 1260,
    death_year: 1340,
    number: null,
    birth_place_id: 2,
    death_place_id: 1,
    mother_id: null,
    type_mother: TypeMother.alawi,
    number_mother: null,
    name_mother: 'خديجة بنت عمر',
    note: '',
    file: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 6,
    name: 'حسين بن محمد',
    kunya: 'أبو علي',
    title: '',
    gender: 'M' as Gender,
    parent_id: 2,
    type_person: TypePerson.included,
    birth_year: 1265,
    death_year: 1345,
    number: null,
    birth_place_id: 1,
    death_place_id: 3,
    mother_id: null,
    type_mother: TypeMother.al_Bayt,
    number_mother: null,
    name_mother: '',
    note: 'انتقل إلى المكلا',
    file: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 7,
    name: 'عمر بن محمد',
    kunya: '',
    title: 'الفقيه',
    gender: 'M' as Gender,
    parent_id: 2,
    type_person: TypePerson.punish_extinct,
    birth_year: 1270,
    death_year: 1330,
    number: null,
    birth_place_id: 2,
    death_place_id: 2,
    mother_id: null,
    type_mother: TypeMother.Arab,
    number_mother: null,
    name_mother: 'عائشة',
    note: '',
    file: null,
    created_at: now,
    updated_at: now,
  },
  // الجيل الرابع
  {
    id: 8,
    name: 'حسن بن علي',
    kunya: 'أبو محمد',
    title: 'الحبيب',
    gender: 'M' as Gender,
    parent_id: 5,
    type_person: TypePerson.included,
    birth_year: 1290,
    death_year: 1370,
    number: null,
    birth_place_id: 1,
    death_place_id: 1,
    mother_id: 4,
    type_mother: TypeMother.alawi,
    number_mother: null,
    name_mother: '',
    note: '',
    file: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 9,
    name: 'أبوبكر بن علي',
    kunya: 'أبو عمر',
    title: '',
    gender: 'M' as Gender,
    parent_id: 5,
    type_person: TypePerson.contract,
    birth_year: 1295,
    death_year: 1360,
    number: null,
    birth_place_id: 1,
    death_place_id: 7,
    mother_id: null,
    type_mother: TypeMother.foreign,
    number_mother: 1,
    name_mother: 'مريم',
    note: 'هاجر إلى مكة',
    file: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 10,
    name: 'زينب بنت علي',
    kunya: '',
    title: '',
    gender: 'F' as Gender,
    parent_id: 5,
    type_person: TypePerson.females_only,
    birth_year: 1292,
    death_year: 1355,
    number: 2,
    birth_place_id: 2,
    death_place_id: 1,
    mother_id: null,
    type_mother: TypeMother.alawi,
    number_mother: null,
    name_mother: '',
    note: '',
    file: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 11,
    name: 'سالم بن حسين',
    kunya: 'أبو عبدالرحمن',
    title: 'الشيخ',
    gender: 'M' as Gender,
    parent_id: 6,
    type_person: TypePerson.included,
    birth_year: 1295,
    death_year: 1380,
    number: null,
    birth_place_id: 3,
    death_place_id: 3,
    mother_id: null,
    type_mother: TypeMother.walad,
    number_mother: null,
    name_mother: '',
    note: '',
    file: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 12,
    name: 'عبدالرحمن بن حسين',
    kunya: '',
    title: '',
    gender: 'M' as Gender,
    parent_id: 6,
    type_person: TypePerson.extinct_females_only,
    birth_year: 1300,
    death_year: 1365,
    number: null,
    birth_place_id: 3,
    death_place_id: 4,
    mother_id: null,
    type_mother: TypeMother.unknown,
    number_mother: null,
    name_mother: '',
    note: 'انقرض عقبه وبقيت بناته',
    file: null,
    created_at: now,
    updated_at: now,
  },
  // الجيل الخامس
  {
    id: 13,
    name: 'طه بن حسن',
    kunya: 'أبو الفضل',
    title: 'العلامة',
    gender: 'M' as Gender,
    parent_id: 8,
    type_person: TypePerson.included,
    birth_year: 1320,
    death_year: 1400,
    number: null,
    birth_place_id: 1,
    death_place_id: 1,
    mother_id: 10,
    type_mother: TypeMother.alawi,
    number_mother: null,
    name_mother: '',
    note: 'عالم مشهور في تريم',
    file: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 14,
    name: 'عقيل بن حسن',
    kunya: '',
    title: '',
    gender: 'M' as Gender,
    parent_id: 8,
    type_person: TypePerson.brotherhood_agreement,
    birth_year: 1325,
    death_year: 1390,
    number: null,
    birth_place_id: 1,
    death_place_id: 8,
    mother_id: null,
    type_mother: TypeMother.al_Bayt,
    number_mother: null,
    name_mother: 'هند بنت سعيد',
    note: '',
    file: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 15,
    name: 'خالد بن سالم',
    kunya: 'أبو سعيد',
    title: '',
    gender: 'M' as Gender,
    parent_id: 11,
    type_person: TypePerson.included,
    birth_year: 1330,
    death_year: 1410,
    number: null,
    birth_place_id: 3,
    death_place_id: 10,
    mother_id: null,
    type_mother: TypeMother.Arab,
    number_mother: null,
    name_mother: 'سارة',
    note: 'هاجر إلى جاكرتا',
    file: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 16,
    name: 'آمنة بنت حسن',
    kunya: '',
    title: '',
    gender: 'F' as Gender,
    parent_id: 8,
    type_person: TypePerson.females_only,
    birth_year: 1318,
    death_year: 1395,
    number: 4,
    birth_place_id: 1,
    death_place_id: 1,
    mother_id: null,
    type_mother: TypeMother.alawi,
    number_mother: null,
    name_mother: '',
    note: '',
    file: null,
    created_at: now,
    updated_at: now,
  },
];

// ===== Mock Wives =====
export const mockWives: Wife[] = [
  {
    id: 1,
    person_id: 1,
    the_wife_id: null,
    number: 1,
    name: 'خديجة بنت محمد',
    birth_year: 1210,
    death_year: 1275,
    birth_place_id: 1,
    death_place_id: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: 2,
    person_id: 2,
    the_wife_id: null,
    number: 2,
    name: 'فاطمة بنت حسين',
    birth_year: 1238,
    death_year: 1305,
    birth_place_id: 1,
    death_place_id: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: 3,
    person_id: 2,
    the_wife_id: null,
    number: 3,
    name: 'عائشة بنت سالم',
    birth_year: 1245,
    death_year: 1315,
    birth_place_id: 2,
    death_place_id: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: 4,
    person_id: 5,
    the_wife_id: null,
    number: 4,
    name: 'زهراء بنت عبدالله',
    birth_year: 1268,
    death_year: 1340,
    birth_place_id: 1,
    death_place_id: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: 5,
    person_id: 8,
    the_wife_id: null,
    number: 5,
    name: 'سكينة بنت أحمد',
    birth_year: 1295,
    death_year: 1370,
    birth_place_id: 1,
    death_place_id: 1,
    created_at: now,
    updated_at: now,
  },
];

// ===== Mock Sources =====
export const mockSources: Source[] = [
  {
    id: 1,
    person_id: 1,
    name: 'شمس الظهيرة',
    capt_number: '102',
    shelf_number: 'أ-3',
    volume_number: '1',
    manuscript_number: '45',
    page_number: '78',
    file: null,
    is_primary: true,
    description: 'المصدر الأصلي لسلسلة النسب',
    created_at: now,
    updated_at: now,
  },
  {
    id: 2,
    person_id: 2,
    name: 'المشرع الروي',
    capt_number: '205',
    shelf_number: 'ب-1',
    volume_number: '2',
    manuscript_number: '67',
    page_number: '134',
    file: null,
    is_primary: true,
    description: 'مصدر أساسي في الأنساب',
    created_at: now,
    updated_at: now,
  },
  {
    id: 3,
    person_id: 5,
    name: 'خلاصة الأثر',
    capt_number: '310',
    shelf_number: 'ج-2',
    volume_number: '3',
    manuscript_number: '89',
    page_number: '201',
    file: null,
    is_primary: false,
    description: 'نقل عن مصدر أصلي',
    created_at: now,
    updated_at: now,
  },
  {
    id: 4,
    person_id: 8,
    name: 'عقد الجواهر والدرر',
    capt_number: '415',
    shelf_number: 'د-4',
    volume_number: '1',
    manuscript_number: '23',
    page_number: '56',
    file: null,
    is_primary: true,
    description: '',
    created_at: now,
    updated_at: now,
  },
];
